#!/bin/sh
#
# An example hook script to verify what is about to be pushed.
# Called by "git push" with no arguments.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the push.
#
# To enable this hook, rename this file to "pre-push".

remote="$1"
url="$2"

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	echo "Pre-push hook: Running tests before pushing..."
	# Run tests
	# pytest
	# if [ $? -ne 0 ]; then
	# 	echo "Tests failed. Please fix the issues before pushing."
	# 	exit 1
	# fi
fi

exit 0
